language: dart

dart:
  - stable

os:
  - linux

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid-fallback

cache:
  directories:
    - $HOME/.pub-cache

env:
  - FLUTTER_VERSION=master

before_script:
  - pwd
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - ./flutter/bin/flutter doctor

script:
- pwd
- ./tool/travis.sh notus
- ./tool/travis.sh zefyr
- bash <(curl -s https://codecov.io/bash)
