include: package:lints/recommended.yaml

linter:
  rules:
    always_declare_return_types: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unawaited_futures: true
    unsafe_html: true
