analyzer:
  strong-mode:
    implicit-dynamic: false

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - avoid_init_to_null
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - prefer_final_fields
    - prefer_is_not_empty
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
